# Copyright 2019 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3.6'

services:

# -------------=== qos-blockchain ===-------------

  qos-blockchain-@nm@:
    image: qosblockchainv1
    container_name: sth-qosblockchain-@nm@
    network_mode: "host"
    command: python3 main.py -C tcp://0.0.0.0:@vp@
    stop_signal: SIGKILL

# -------------=== rest api ===-------------

  rest-api-@nm@:
    image: hyperledger/sawtooth-rest-api:chime
    container_name: sth-rest-api-@nm@
    network_mode: "host"
    command: |
      bash -c "
        sawtooth-rest-api \
          --connect tcp://0.0.0.0:@vp@ \
          --bind 0.0.0.0:@rp@
      "
    stop_signal: SIGKILL

# -------------=== settings tp ===-------------

  settings-tp-@nm@:
    image: hyperledger/sawtooth-settings-tp:chime
    container_name: sth-settings-tp-@nm@
    network_mode: "host"
    command: settings-tp -C tcp://0.0.0.0:@vp@
    stop_signal: SIGKILL

# -------------=== validators ===-------------

  validator-@nm@:
    image: hyperledger/sawtooth-validator:chime
    container_name: sth-validator-@nm@
    network_mode: "host"
    command: |
      bash -c "
        if [ ! -e /etc/sawtooth/keys/validator.priv ]; then
          echo @pub@ > /etc/sawtooth/keys/validator.pub
          echo @pri@ > /etc/sawtooth/keys/validator.priv
        fi &&
        if [ ! -e /etc/sawtooth/keys/validator-1.pub ]; then
          echo @pub1@ > /etc/sawtooth/keys/validator-1.pub
          echo @pub2@ > /etc/sawtooth/keys/validator-2.pub
          echo @pub3@ > /etc/sawtooth/keys/validator-3.pub
        fi &&
        if [ ! -e config-genesis.batch ]; then
          sawset genesis -k /etc/sawtooth/keys/validator.priv -o config-genesis.batch
        fi &&
        if [ ! -e config.batch ]; then
          sawset proposal create \
              -k /etc/sawtooth/keys/validator.priv \
              sawtooth.consensus.algorithm.name=pbft \
              sawtooth.consensus.algorithm.version=1.0 \
              sawtooth.consensus.pbft.members=\\['\"'$$(cat /etc/sawtooth/keys/validator.pub)'\"','\"'$$(cat /etc/sawtooth/keys/validator-1.pub)'\"','\"'$$(cat /etc/sawtooth/keys/validator-2.pub)'\"','\"'$$(cat /etc/sawtooth/keys/validator-3.pub)'\"'\\] \
              sawtooth.publisher.max_batches_per_block=1200 \
              -o config.batch
        fi &&
        if [ ! -e /var/lib/sawtooth/genesis.batch ]; then
          sawadm genesis config-genesis.batch config.batch
        fi &&
        if [ ! -e /root/.sawtooth/keys/my_key.priv ]; then
          sawtooth keygen my_key
        fi &&
        sawtooth-validator -vv \
          --endpoint tcp://@ep@:@np@ \
          --bind component:tcp://0.0.0.0:@vp@ \
          --bind consensus:tcp://0.0.0.0:@cp@ \
          --bind network:tcp://0.0.0.0:@np@ \
          --scheduler parallel \
          --peering static \
          --maximum-peer-connectivity 4 @peers@ 
      "


# -------------=== pbft engines ===-------------

  pbft-@nm@:
    image: hyperledger/sawtooth-pbft-engine:chime
    network_mode: "host"
    container_name: sth-pbft-@nm@
    command: pbft-engine -vv --connect tcp://0.0.0.0:@cp@
    stop_signal: SIGKILL

# -------------=== shell ===-------------

  shell:
    image: hyperledger/sawtooth-shell:chime
    container_name: sawtooth-shell-default
    network_mode: "host"
    command: |
      bash -c "
        sawtooth keygen
        tail -f /dev/null
      "
    stop_signal: SIGKILL